import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import { format } from 'date-fns';

interface ReceiptData {
  receiptNo: string;
  studentName: string;
  studentCourse: string;
  amount: number;
  date: Date;
  method: string;
  notes?: string;
  recordedBy?: string;
}

export const generateReceiptPDF = async (data: ReceiptData) => {
  // Create a hidden container for the receipt
  const receiptContainer = document.createElement('div');
  receiptContainer.style.position = 'fixed';
  receiptContainer.style.left = '-10000px';
  receiptContainer.style.top = '0';
  receiptContainer.style.width = '800px';
  receiptContainer.style.padding = '40px';
  receiptContainer.style.backgroundColor = '#ffffff';
  receiptContainer.style.color = '#000000';
  receiptContainer.style.fontFamily = "'Inter', sans-serif";
  
  const logoUrl = "https://kommodo.ai/i/72EuMuVxBrOvNd3WZNHq";

  receiptContainer.innerHTML = `
    <div style="border: 4px solid #0A0F1C; padding: 30px; position: relative; overflow: hidden;">
      <!-- Watermark Logo -->
      <img src="${logoUrl}" crossOrigin="anonymous" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); width: 400px; opacity: 0.05; pointer-events: none;" />
      
      <!-- Header -->
      <div style="display: flex; justify-content: space-between; align-items: start; border-bottom: 2px solid #eee; padding-bottom: 20px; margin-bottom: 30px;">
        <div style="display: flex; gap: 20px; align-items: center;">
          <img src="${logoUrl}" crossOrigin="anonymous" style="width: 80px; height: 80px; object-contain;" />
          <div>
            <h1 style="margin: 0; font-size: 28px; font-weight: 900; text-transform: uppercase; letter-spacing: -1px; color: #0A0F1C;">Charthess</h1>
            <p style="margin: 0; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 4px; color: #1CA3B8;">School of Fashion</p>
            <p style="margin: 5px 0 0 0; font-size: 12px; color: #666;">Accra, Ghana | +233 24 123 4567</p>
          </div>
        </div>
        <div style="text-align: right;">
          <h2 style="margin: 0; font-size: 24px; font-weight: 900; color: #1CA3B8; text-transform: uppercase;">Official Receipt</h2>
          <p style="margin: 5px 0 0 0; font-weight: bold;">No: ${data.receiptNo}</p>
          <p style="margin: 2px 0 0 0; font-size: 12px; color: #666;">Date: ${format(data.date, 'PPPP')}</p>
        </div>
      </div>

      <!-- Content -->
      <div style="margin-bottom: 40px;">
        <div style="display: grid; grid-template-columns: 150px 1fr; gap: 15px; margin-bottom: 10px;">
          <div style="font-weight: bold; color: #888; text-transform: uppercase; font-size: 12px;">Received From:</div>
          <div style="font-size: 18px; font-weight: bold; border-bottom: 1px dashed #eee; padding-bottom: 5px;">${data.studentName}</div>
        </div>
        <div style="display: grid; grid-template-columns: 150px 1fr; gap: 15px; margin-bottom: 10px;">
          <div style="font-weight: bold; color: #888; text-transform: uppercase; font-size: 12px;">Course:</div>
          <div style="font-size: 16px; border-bottom: 1px dashed #eee; padding-bottom: 5px;">${data.studentCourse}</div>
        </div>
        <div style="display: grid; grid-template-columns: 150px 1fr; gap: 15px; margin-bottom: 10px;">
          <div style="font-weight: bold; color: #888; text-transform: uppercase; font-size: 12px;">The Sum Of:</div>
          <div style="font-size: 24px; font-weight: 900; color: #0A0F1C; border-bottom: 1px dashed #eee; padding-bottom: 5px;">GH₵ ${data.amount.toLocaleString()}.00</div>
        </div>
        <div style="display: grid; grid-template-columns: 150px 1fr; gap: 15px; margin-bottom: 10px;">
          <div style="font-weight: bold; color: #888; text-transform: uppercase; font-size: 12px;">Being Payment For:</div>
          <div style="font-size: 16px; border-bottom: 1px dashed #eee; padding-bottom: 5px;">${data.notes || 'School Academic & Practical Fees'}</div>
        </div>
        <div style="display: grid; grid-template-columns: 150px 1fr; gap: 15px; margin-bottom: 10px;">
          <div style="font-weight: bold; color: #888; text-transform: uppercase; font-size: 12px;">Payment Method:</div>
          <div style="font-size: 16px; text-transform: capitalize;">${data.method}</div>
        </div>
      </div>

      <!-- Footer -->
      <div style="display: flex; justify-content: space-between; align-items: end; margin-top: 60px;">
        <div style="font-size: 12px; color: #999;">
          <p style="margin: 0;">This is a computer-generated receipt.</p>
          <p style="margin: 0;">Generated by: ${data.recordedBy || 'System'}</p>
        </div>
        <div style="text-align: center;">
          <div style="width: 200px; border-bottom: 2px solid #0A0F1C; margin-bottom: 10px;"></div>
          <p style="margin: 0; font-weight: bold; text-transform: uppercase; font-size: 12px;">Authorized Signature</p>
        </div>
      </div>
      
      <div style="margin-top: 40px; text-align: center; font-size: 10px; color: #bbb; text-transform: uppercase; letter-spacing: 2px;">
        Empowering Fashion Excellence
      </div>
    </div>
  `;

  document.body.appendChild(receiptContainer);

  try {
    const canvas = await html2canvas(receiptContainer, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff'
    });
    
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgProps = pdf.getImageProperties(imgData);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
    
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
    pdf.save(`Receipt_${data.receiptNo}_${data.studentName.replace(/ /g, '_')}.pdf`);
  } finally {
    document.body.removeChild(receiptContainer);
  }
};
